delete Provincia
delete Localidad 
delete Pais 
delete Fuerza 
delete Grado 
delete Guarnicion 
delete Unidad
delete Estado
delete SituacionFamiliar
delete EstadoCivil
delete TipoContacto
delete Escolaridad
delete Genero
delete Parentesco
delete SituacionLaboral
delete TipoDocumento
delete TipoDocumentoAdjunto
delete TipoExpediente
